library: /mnt/qnap/Music/beets.db
directory: /mnt/qnap/Music/Music

plugins: embedart fetchart lastgenre musicbrainz

embedart:
  auto: yes

fetchart:
  auto: yes
  sources:
    - filesystem
    - coverart: release
    - itunes
    - amazon
    - albumart
    - coverart: releasegroup
    - spotify
    - wikipedia
    - lastfm

lastgenre:
    auto: yes
    canonical: yes
    count: 1
    prefer_specific: yes
    source: album
    whitelist: yes
