library: /mnt/qnap/Music/beets.db
directory: /mnt/qnap/Music/Music

plugins: embedart fetchart musicbrainz

fetchart:
  auto: yes
  sources: coverart itunes amazon albumart filesystem

embedart:
  auto: yes
