library: /mnt/qnap/Music/beets.db
directory: /mnt/qnap/Music/Music

plugins: embedart fetchart musicbrainz

fetchart:
  auto: yes
  sources:
    - filesystem
    - coverart: release
    - itunes
    - amazon
    - albumart
    - coverart: releasegroup
    - spotify
    - wikipedia
    - lastfm

embedart:
  auto: yes
